foreground #e7e6e6
background #111010
cursor #e7e6e6

selection_background #3A3835
selection_foreground #e7e6e6
background_opacity 0.85

color0 #111010
color8 #a1a1a1

color1 #8C897C
color9 #8C897C

color2 #7D8383
color10 #7D8383

color3 #8F928C
color11 #8F928C

color4 #AAAAA3
color12 #AAAAA3

color5 #C7BCAE
color13 #C7BCAE

color6 #D2D1D2
color14 #D2D1D2

color7 #e7e6e6
color15 #e7e6e6
