theme[main_bg]="#111010"
theme[main_fg]="#c2c2b0"

theme[title]="#c2c2b0"
theme[hi_fg]="#c2c2b0"
theme[selected_bg]="#1A1919"
theme[selected_fg]="#a0927e"

theme[inactive_fg]="#776b5b"

theme[graph_text]="#c2c2b0"
theme[meter_bg]="#554c41"

theme[proc_misc]="#c2c2b0"
theme[cpu_box]="#c2c2b0"
theme[mem_box]="#c2c2b0"
theme[net_box]="#c2c2b0"
theme[proc_box]="#c2c2b0"

theme[div_line]="#554c41"

theme[temp_start]="#c2c2b0"
theme[temp_mid]="#a0927e"
theme[temp_end]="#776b5b"

theme[cpu_start]="#c2c2b0"
theme[cpu_mid]="#a0927e"
theme[cpu_end]="#776b5b"

theme[free_start]="#c2c2b0"
theme[free_mid]="#a0927e"
theme[free_end]="#776b5b"

theme[cached_start]="#c2c2b0"
theme[cached_mid]="#a0927e"
theme[cached_end]="#776b5b"

theme[available_start]="#c2c2b0"
theme[available_mid]="#a0927e"
theme[available_end]="#776b5b"

theme[used_start]="#c2c2b0"
theme[used_mid]="#a0927e"
theme[used_end]="#776b5b"

theme[download_start]="#c2c2b0"
theme[download_mid]="#a0927e"
theme[download_end]="#776b5b"

theme[upload_start]="#c2c2b0"
theme[upload_mid]="#a0927e"
theme[upload_end]="#776b5b"

theme[process_start]="#c2c2b0"
theme[process_mid]="#a0927e"
theme[process_end]="#776b5b"
